<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use DateTimeInterface;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Image\Exceptions\InvalidManipulation;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Car extends Model implements HasMedia
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use InteractsWithMedia;
    use HasFactory;
    use Sluggable;

    public const STATUS_SELECT = [
        '1' => 'For sale',
        '2' => 'For rent',
        '3' => 'Sold out',
        '4' => 'Rented out',
    ];

    public $table = 'cars';

    protected $appends = [
        'car_image',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'slug',
        'model_year',
        'price',
        'seats',
        'description',
        'status',
        'approved',
        'location_id',
        'team_id',
        'address',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * @throws InvalidManipulation
     */
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 250, 250);
        $this->addMediaConversion('preview')->fit('crop', 1400, 700);
    }

    public function getCarImageAttribute(): MediaCollection
    {
        $files = $this->getMedia('car_image');
        $files->each(function ($item) {
            $item->url = $item->getUrl();
            $item->thumbnail = $item->getUrl('thumb');
            $item->preview = $item->getUrl('preview');
        });

        return $files;
    }

    public function location():BelongsTo
    {
        return $this->belongsTo(Location::class, 'location_id');
    }

    public function infos() :HasOne
    {
        return $this->hasOne(VehicleInfo::class);
    }

    public function created_by() :BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }
    public static  function  boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($car) {
            $car->infos()->create([
                'title' => $car->title,
            ]);
        });
    }

    protected function serializeDate(DateTimeInterface $date): string
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function sluggable(): array
    {
        return [
            'slug'=>[
                'source'=>'title'
            ]

        ];
    }
    public function scopeMightAlsoLike($query)
    {
        return $query->inRandomOrder()->take(6);
    }
}
